### ISSUE TITLE
problemas

### ISSUE THREAD

**Issue by sna1988** [seansa/Biometrico#11]
Rita ahi tengo un par de errores en lo que subiste nuevo.... en la parte del metodo VerificarExisteEnMemoria me dice que no estas pasando el parametro de horarioParcial que es bool, como que le falta ese parametro para hacer el metodo
y en el principal tengo un new PresentacionBase().myFont o algo asi que me esta tirando error 
despues fijate y decime q onda porq no lo puedo compilar al proyecto sino

**Comment by Widcket** [comment]
En que archivo?

**Comment by sna1988** [comment]
private void LogIn_Load(object sender, EventArgs e)
        {
            this.txtUsuario.Text = "ADMIN";
            this.txtPassword.Text = "123";
            lblTitulo.Font = new FormularioBase().myFont;
        }

en esto me esta tirando error en el myFont

**Comment by sna1988** [comment]
private void btnAgregar_Click(object sender, EventArgs e)
        {

```
        if (_comisionServicio.VerificarNoEsteRepetidoMemoria(listaTemporal, this.dtpFechaDesde.Value, this.dtpFechaHasta.Value))
        {

            var _nuevaComision = new ComisionServicioDTO()
            {
                AgenteId = this.AgenteId,
                FechaDesde = this.dtpFechaDesde.Value,
                FechaHasta = this.dtpFechaHasta.Value,
                Observaciones = this.txtObservaciones.Text,

            };
            listaTemporal.Add(_nuevaComision);
        }
        else
        {
            MessageBox.Show("Se Repite");
        }
        this.dgvGrilla.DataSource = listaTemporal.ToList();
    }
```

y en este metodo que dice q t estan faltando pasar parametros

**Comment by Widcket** [comment]
No los puedo reproducir, me compila bien

**Comment by Widcket** [comment]
Ahora sí, cuando hice pull desde origin y sincronizé los últimos cambios, me dio error en la fuente, ya está corregido. Raro, hoy no toqué nada de eso
